// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfTV0PVenhT4uINOTWqT6HYY0rRzRXTE',
    appId: '1:291039547391:web:d954c56cdab0db3b0d61ca',
    messagingSenderId: '291039547391',
    projectId: 'aquatrackium-98fc3',
    authDomain: 'aquatrackium-98fc3.firebaseapp.com',
    storageBucket: 'aquatrackium-98fc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4BIndXN9mmcObeHkcYA00RQHC1Q7zpc',
    appId: '1:291039547391:android:35a59ab001a0514f0d61ca',
    messagingSenderId: '291039547391',
    projectId: 'aquatrackium-98fc3',
    storageBucket: 'aquatrackium-98fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYtFJ_m92KTFc65r7b5OJvm5qgBzTRME',
    appId: '1:291039547391:ios:7cbe665fc71b05e60d61ca',
    messagingSenderId: '291039547391',
    projectId: 'aquatrackium-98fc3',
    storageBucket: 'aquatrackium-98fc3.appspot.com',
    iosBundleId: 'com.example.aquatrackium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGYtFJ_m92KTFc65r7b5OJvm5qgBzTRME',
    appId: '1:291039547391:ios:47ebc0cf991d949c0d61ca',
    messagingSenderId: '291039547391',
    projectId: 'aquatrackium-98fc3',
    storageBucket: 'aquatrackium-98fc3.appspot.com',
    iosBundleId: 'com.example.aquatrackium.RunnerTests',
  );
}
